# Generated by Django 3.0.5 on 2020-04-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bill_billcategory_genericexpense_genericexpensecategory_goal_paymentmethod_payroll_payrollcategory_p'),
        ('blog', '0002_goaltype'),
    ]

    operations = [
    ]
