# Generated by Django 3.0.5 on 2020-04-27 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_merge_20200413_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_payroll', to=settings.AUTH_USER_MODEL),
        ),
    ]
